import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started',
        'setup-guide',
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      collapsed: false,
      items: [
        'agents/advisor',
        'agents/author',
        'agents/manage',
        'agents/test',
      ],
    },
    {
      type: 'category',
      label: 'Patterns',
      items: [
        { type: 'autogenerated', dirName: 'patterns' },
      ],
    },
    {
      type: 'category',
      label: 'Skills',
      items: [
        'skills/overview',
        'skills/authoring',
        'skills/deployment',
        'skills/testing',
        'skills/utilities',
      ],
    },
    {
      type: 'category',
      label: 'Templates',
      items: [
        'templates/overview',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/project-structure',
        'reference/schema',
      ],
    },
    'troubleshooting',
    'cat-resources',
    'changelog',
  ],
};

export default sidebars;
